name: Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ahorgnies
          password: ${{ secrets.DOCKERIO_TOKEN }}
      - name: Declare some variables
        shell: bash
        run: |
          echo "SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ahorgnies/dtp:${{ env.SHORT_SHA }}
          cache-from: type=gha
